### ISSUE TITLE
main crashing with NullPointerException

### ISSUE THREAD

**Issue by rafifos** [FlymeOS/devices-base_cm#13]
This seems to be related to two problems..

from logcat: 

> 03-27 08:10:57.066  3297  3297 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
> 03-27 08:10:57.066  3297  3297 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'void android.webkit.IWebViewUpdateService.notifyRelroCreationCompleted(boolean, boolean)' on a null object reference
> 03-27 08:10:57.066  3297  3297 E AndroidRuntime: 	at android.webkit.WebViewFactory$RelroFileCreator.main(WebViewFactory.java:491)
> 03-27 08:10:57.066  3297  3297 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
> 03-27 08:10:57.066  3297  3297 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
> 03-27 08:10:57.066  3297  3297 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
> 03-27 08:10:57.068  3297  3297 E AndroidRuntime: Error reporting crash
> 03-27 08:10:57.068  3297  3297 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'void android.app.IActivityManager.handleApplicationCrash(android.os.IBinder, android.app.ApplicationErrorReport$CrashInfo)' on a null object reference
> 03-27 08:10:57.068  3297  3297 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:95)
> 03-27 08:10:57.068  3297  3297 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
> 03-27 08:10:57.068  3297  3297 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)

**Comment by rafifos** [comment]
Closed, see https://github.com/FlymeOS/devices-base_cm/issues/11
